% Batch run classify_each_subject for multiple masks & other parameters
% potentially in order to precompute & save the results
% similar to classify_each_subject.sh
%

masks = {fullfile('masks', 'hippocampus.nii'), ...
         fullfile('masks', 'ofc.nii'), ...
         fullfile('masks', 'striatum.nii'), ...
         fullfile('masks', 'vmpfc.nii'), ...
         fullfile('masks', 'bg.nii'), ...
         fullfile('masks', 'pallidum.nii'), ...
         fullfile('masks', 'v1.nii'), ...
         fullfile('masks', 'visual.nii'), ...
         fullfile('masks', 'motor.nii'), ...
         fullfile('masks', 'sensory.nii')};
z_scores = {'z-run'};

% Run computation for each mask
%
for mask = masks
    mask = mask{1};
    
    for z_score = z_scores
        z_score = z_score{1};
        
        classify_each_subject(mask, z_score); 
    end
end
