% Batch run classify_single_subject for multiple masks & other parameters
% potentially in order to precompute & save the results
% similar to classify_single_subject.sh
%

masks = {fullfile('masks', 'hippocampus.nii'), ...
         fullfile('masks', 'ofc.nii'), ...
         fullfile('masks', 'striatum.nii'), ...
         fullfile('masks', 'vmpfc.nii'), ...
         fullfile('masks', 'bg.nii'), ...
         fullfile('masks', 'pallidum.nii'), ...
         fullfile('masks', 'visual.nii'), ...
         fullfile('masks', 'motor.nii'), ...
         fullfile('masks', 'sensory.nii')};
z_score = 'z-run';

% Run computation for each mask
%
for mask = masks
    mask = mask{1};
    
    classify_single_subject(mask, z_score); 
end