% convert a XLS Result Table with ROIs generated by bspmview into a LaTeX
% table
%


% Anatomical region name, AAL2 label
% Table 2 from Implementation of a new parcellation of the orbitofrontal cortex in the
% automated anatomical labeling atlas (NeuroImage, 2015)
%
ROIs = {'Precentral gyrus',  'Precentral' ;
'Postcentral gyrus',  'Postcentral' ;
'Rolandic operculum',  'Rolandic_Oper' ;
'Superior frontal gyrus, dorsolateral',  'Frontal_Sup' ;
'Middle frontal gyrus',  'Frontal_Mid' ;
'Inferior frontal gyrus, opercular part',  'Frontal_Inf_Oper' ;
'Inferior frontal gyrus, triangular part',  'Frontal_Inf_Tri' ;
'Superior frontal gyrus, medial',  'Frontal_Sup_Med' ;
'Supplementary motor area',  'Supp_Motor_Area' ;
'Paracentral lobule',  'Paracentral_Lobule' ;
'Superior frontal gyrus, medial orbital',  'Frontal_Med_Orb' ;
'IFG pars orbitalis',  'Frontal_Inf_Orb' ;
'Gyrus rectus',  'Rectus' ;
'Medial orbital gyrus',  'OFCmed' ;
'Anterior orbital gyrus',  'OFCant' ;
'Posterior orbital gyrus',  'OFCpost' ;
'Lateral orbital gyrus',  'OFClat' ;
'Olfactory cortex',  'Olfactory' ;
'Superior temporal gyrus',  'Temporal_Sup' ;
'Heschl''s gyrus',  'Heschl' ;
'Middle temporal gyrus',  'Temporal_Mid' ;
'Inferior temporal gyrus',  'Temporal_Inf' ;
'Superior parietal gyrus',  'Parietal_Sup' ;
'Inferior parietal gyrus, excluding supramarginal and angular gyri',  'Parietal_Inf' ;
'Angular gyrus',  'Angular' ;
'Supramarginal gyrus',  'SupraMarginal',;
'Precuneus',  'Precuneus' ;
'Superior occipital gyrus',  'Occipital_Sup' ;
'Middle occipital gyrus',  'Occipital_Mid' ;
'Inferior occipital gyrus',  'Occipital_Inf' ;
'Cuneus',  'Cuneus' ;
'Calcarine fissure and surrounding cortex',  'Calcarine' ;
'Lingual gyrus',  'Lingual' ;
'Fusiform gyrus',  'Fusiform' ;
'Temporal pole: superior temporal gyrus',  'Temporal_Pole_Sup' ;
'Temporal pole: middle temporal gyrus',  'Temporal_Pole_Mid' ;
'Anterior cingulate \& paracingulate gyri',  'Cingulate_Ant' ;
'Middle cingulate \& paracingulate gyri',  'Cingulate_Mid' ;
'Posterior cingulate gyrus',  'Cingulate_Post' ;
'Hippocampus',  'Hippocampus';
'Parahippocampal gyrus',  'ParaHippocampal' ;
'Insula',  'Insula' ;
'Amygdala',  'Amygdala' ;
'Caudate nucleus',  'Caudate' ;
'Lenticular nucleus, Putamen',  'Putamen' ;
'Lenticular nucleus, Pallidum',  'Pallidum' ;
'Thalamus',  'Thalamus' };


[num, txt, raw] = xlsread('../paper/save_table_spmT_0001_PosNeg_I3.5794_C176_S20.xlsx');

rows = size(num, 1);
txt = txt(end-rows+1:end, :);

for i=1:rows
    roi_label = txt{i,2};
    roi = [];
    for j=1:size(ROIs, 1)
        if startsWith(roi_label, ROIs{j, 2})
            roi = ROIs{j, 1};
            break;
        end
    end
    if isempty(roi)
        roi = roi_label;
    else
        s = strsplit(roi_label, '_');
        roi = [roi, ' (', s{end}, ')'];
    end
    fprintf('%s & %s & %d & %.3f & %d %d %d \\\\\n', txt{i,1}, roi, num(i,1), num(i,2), num(i,3), num(i,4), num(i,5));
end

