% same as kl_structure_learning.m but for the weights KL divergence
% TODO dedupe NOTE that we flipped subj_idx and run in the kl_betas_roi and test_liks
%

%% Load behavior
%
[data, metadata] = load_data(fullfile('data', 'fmri.csv'), true, getGoodSubjects());
goodSubjects = getGoodSubjects();
which_rows = data.which_rows;

%% Simulate behavior
%
prior_variance = 0.1249;
inv_softmax_temp = 2.0064;
params = [prior_variance inv_softmax_temp];
which_structures = logical([1 1 1 0]);
simulated = simulate_subjects(data, metadata, params, which_structures, which_rows, false);

%% Some random voxels as controls
%
rand_voxels = gen_rand_voxels(fullfile('masks', 'mask.nii'), 20);

%% The KL_weight betas from GLM 148
%

% The peak voxel from each ROI from the contrast (from the results table) 
%
KL_weights_148_rois = {'Temporal_Inf_L', ...
    'Parietal_Inf_L', ...
	'Temporal_Inf_L', ...
	'Supp_Motor_Area_R', ...
	'Frontal_Sup_Medial_L', ...
	'Supp_Motor_Area_L', ...
	'Location not in atlas', ...
	'Location not in atlas', ...
	'Frontal_Inf_Oper_L', ...
	'Frontal_Mid_2_L', ...
	'Frontal_Inf_Tri_R', ...
	'Frontal_Inf_Tri_R', ...
	'Cerebelum_8_R', ...
	'Frontal_Inf_Orb_2_L', ...
	'Pallidum_L', ...
	'Frontal_Inf_Tri_L'};

KL_weights_peak_148_voxels = [-48    -52    -16; ...
	-32    -56    46; ...
	-42    -34    -28; ...
	10    14    46; ...
	-8    22    42; ...
	-8    10    68; ...
	30    24    0; ...
	16    6    -6; ...
	-42    8    26; ...
	-36    4    58; ...
	36    20    28; ...
	50    34    24; ...
	30    -68    -50; ...
	-46    16    -4; ...
	-20    4    -4; ...
	-44    40    0];

KL_weights_148_betas = load_run_betas(148, 'KL_weights', [KL_weights_peak_148_voxels; rand_voxels]);

%% The KL_structures betas, voxels taken from 'surprise - wrong' contrast from GLM 123
%
KL_structures_error_123_rois = {
    'Angular_R', ...
    'Parietal_Inf_R', ...
    'Frontal_Mid_2_L', ...
    'Location not in atlas', ...
    'Frontal_Mid_2_R', ...
    'OFCmed_R', ...
    'Frontal_Mid_2_R'};

KL_structures_error_123_peak_voxels = [34  -68 52; ...
    40  -46 38; ...
    -42 54  2; ...
    -30 62  22; ...
    36  54  0; ...
    18  42  -16; ...
    52  32  32];

KL_structures_error_123_betas = load_run_betas(123, 'surprise', [KL_structures_error_123_peak_voxels; rand_voxels]);

%% KL_structures betas for 'surprise' contrast only from GLM 123
%
KL_structures_123_rois = { ...
    'Parietal_Sup_R', ...
    'Parietal_Inf_R', ...
    'Location', ...
    'Frontal_Inf_Oper_R', ...
    'Frontal_Mid_2_R', ...
    'Frontal_Mid_2_L', ...
    'Frontal_Sup_2_L', ...
    'Frontal_Inf_Orb_2_L', ...
    'Frontal_Mid_2_R', ...
    'OFCant_R', ...
    'Parietal_Inf_L', ...
    'Parietal_Inf_L', ...
    'Cerebelum_Crus2_L', ...
    'Frontal_Inf_Tri_L', ...
    'Precentral_L', ...
    'Frontal_Mid_2_L', ...
    'Cerebelum_8_L', ...
    'Cerebelum_Crus1_L'};

KL_structures_123_peak_voxels = [ ...
    32    -66    50; ...
    42    -46    40; ...
    32    22    0; ...
    48    22    32; ...
    34    12    52; ...
    -40    56    4; ...
    -24    58    -10; ...
    -46    34    -10; ...
    36    54    0; ...
    20    48    -16; ...
    -30    -62    40; ...
    -46    -38    44; ...
    -6    -78    -30; ...
    -38    16    26; ...
    -38    0    40; ...
    -50    34    28; ...
    -32    -68    -54; ...
    -30    -62    -32];

KL_structures_123_betas = load_run_betas(123, 'surprise', [KL_structures_123_peak_voxels; rand_voxels]);


% The KL_structures from the 'KL_structure' contrast from GLM 151 with the KL_weights
% note that this overwrites the previous one
%

KL_structures_151_rois = { ...
    'Insula_R', ...
    'Angular_R', ...
    'Parietal_Inf_R', ...
    'Occipital_Mid_R', ...
    'Parietal_Inf_L', ...
    'Parietal_Inf_L', ...
    'Frontal_Inf_Oper_R', ...
    'Frontal_Mid_2_R', ...
    'Frontal_Mid_2_L', ...
    'Frontal_Sup_2_L', ...
    'Temporal_Pole_Sup_L', ...
    'Precentral_L', ...
    'Frontal_Inf_Tri_L', ...
    'Frontal_Mid_2_L', ...
    'OFCant_R', ...
    'Frontal_Mid_2_R', ...
    'Supp_Motor_Area_L', ...
    'Frontal_Sup_Medial_L', ...
    'Cerebelum_6_R', ...
    'Fusiform_R', ...
    'Temporal_Inf_R', ...
    'Fusiform_L', ...
    'Cerebelum_Crus2_L', ...
    'Cerebelum_8_L', ...
    'Insula_L', ...
    'Temporal_Inf_R', ...
    'Temporal_Inf_R', ...
    'Lingual_R', ...
    'Cuneus_R', ...
    'Temporal_Mid_L', ...
    'Occipital_Inf_L'};

KL_structures_151_peak_voxels = [...
    32    22    0; ...
    34    -64    48; ...
    44    -46    42; ...
    32    -66    26; ...
    -30    -62    40; ...
    -46    -38    42; ...
    48    20    32; ...
    32    12    50; ...
    -40    56    6; ...
    -24    58    -10; ...
    -46    22    -16; ...
    -42    2    32; ...
    -48    20    20; ...
    -38    12    58; ...
    20    48    -16; ...
    36    54    0; ...
    -6    8    52; ...
    -6    34    38; ...
    18    -70    -24; ...
    34    -42    -20; ...
    46    -58    -24; ...
    -32    -54    -18; ...
    -6    -78    -30; ...
    -32    -68    -54; ...
    -28    24    -2; ...
    62    -24    -22; ...
    58    -60    -20; ...
    12    -96    -8; ...
    12    -98    12; ...
    -58    -36    -4; ...
    -20    -92    -6];

KL_structures_151_betas = load_run_betas(151, 'KL_structures', [KL_structures_151_peak_voxels; rand_voxels]);

% The KL_weights from the 'KL_weights' contrast from GLM 151 with the KL_structures
% note that this overwrites the previous one
%

KL_weights_151_rois = { ...
    'Temporal_Inf_L', ...
    'Parietal_Inf_L', ...
    'Fusiform_L', ...
    'Frontal_Inf_Tri_R', ...
    'Frontal_Inf_Oper_L', ...
    'Frontal_Inf_Tri_L', ...
    'Frontal_Mid_2_L', ...
    'Supp_Motor_Area_L', ...
    'Location not in atlas', ...
    'Thalamus_R', ...
    'Putamen_R', ...
    'Temporal_Mid_L', ...
    'Frontal_Inf_Orb_2_L', ...
    'Putamen_L'};

KL_weights_peak_151_voxels = [ ...
    -50    -52    -16; ...
    -26    -68    44; ...
    -28    -72    -18; ...
    36    20    26; ...
    -42    8    26; ...
    -56    22    20; ...
    -38    4    60; ...
    -8    10    50; ...
    30    26    0; ...
    12    -14    2; ...
    16    8    -6; ...
    -54    -38    -4; ...
    -40    20    -4; ...
    -20    16    -6];

KL_weights_151_betas = load_run_betas(151, 'KL_weights', [KL_weights_peak_151_voxels; rand_voxels]);

%% Get the behavioral correlates
%
test_liks = nan(metadata.N, metadata.runsPerSubject);
test_RTs = nan(metadata.N, metadata.runsPerSubject);

% Iterate over subjects
%
subj_idx = 0; % 1..20
for subj = goodSubjects % 1..25
    subject = metadata.allSubjects(subj); % 'con001' ... 'con025'
    subj_trials = data.which_rows & strcmp(data.participant, subject);
    subj_idx = subj_idx + 1;
    fprintf('subj %d (idx %d)\n', subj, subj_idx);

    % Iterate over runs
    %
    for run = 1:metadata.runsPerSubject
        fprintf(' RUN %d\n', run);
        run_trials = subj_trials & data.runId == run;
        condition = data.contextRole(run_trials);
        condition = condition{1};
		assert(sum(run_trials) == metadata.trialsPerRun);

        % Get the test trial likelihood
        %
        run_test_trials = run_trials & ~data.isTrain & ~data.timeout;
        
        X_fixed = data.chose_sick(run_test_trials); % actual subject choice on each trial
        P = simulated.pred(run_test_trials); % probability of subject choice on each trial
        assert(numel(X_fixed) <= metadata.testTrialsPerRun);
        
        liks = binopdf(X_fixed, 1, P);
        assert(numel(liks) == numel(X_fixed));
        avg_loglik = mean(log(liks)); % average to account for timeouts
        
        test_liks(subj_idx, run) = avg_loglik; 
        
        % Get the test trial RTs
        %
        test_RTs(subj_idx, run) = mean(data.response.rt(run_test_trials));
    end
end


save('results/kl_stuff_151.mat');

%% within-subject analysis using a linear mixed effects model and/or t-tests
%

load('results/kl_stuff_151.mat');

% pick which one to analyze TODO refactor
%
analyze_KL_weights_and_not_KL_structures = true; % #KNOB

if analyze_KL_weights_and_not_KL_structures
    KL_betas = KL_weights_148_betas;
    rois = KL_weights_148_rois;
   % KL_betas = KL_weights_151_betas;
   % rois = KL_weights_151_rois;
    plot_what = 'KL_weights';
else
    KL_betas = KL_structures_123_betas;
    rois = KL_structures_123_rois;
  %  KL_betas = KL_structures_151_betas;
  %  rois = KL_structures_151_rois;
    plot_what = 'KL_structures';
end

% Do the correlations
%

lmes = {};
lme_means = [];
lme_sems = [];
lme_ps = [];

ttest_means = [];
ttest_sems = [];
ttest_ps = [];

all_fisher_rs = {};

for roi = 1:size(KL_betas, 3)
    kl_betas_roi = KL_betas(:, :, roi);

    lme_liks = [];
    lme_betas = [];
    lme_ids = [];
    
    fisher_rs = [];

    for subj_idx = 1:metadata.N
        x = test_liks(subj_idx, :)';
        y = kl_betas_roi(subj_idx, :)';
        
        %x = zscore(x);
        %y = zscore(y);

        % LME model within-subject analysis
        %
        lme_liks = [lme_liks; x];
        lme_betas = [lme_betas; y];
        lme_ids = [lme_ids; ones(size(x,1),1) * subj_idx];
        
        % Simple within-subject t-test
        %
        r = corrcoef(x, y);
        r = r(1,2);
        fisher_r = atanh(r);
        fisher_rs = [fisher_rs; fisher_r];
    end

    % LME model
    %
    tbl = array2table([lme_betas, lme_liks, lme_ids], 'VariableNames', {'Beta', 'Likelihood', 'Subject'});
    %formula = 'Beta ~ Likelihood + (Likelihood|Subject)';
    formula = 'Beta ~ Likelihood + (Likelihood|Subject)';
    lme = fitlme(tbl, formula);
    lmes{roi} = lme;

    p = lme.Coefficients(2, 'pValue').pValue;
    coef = lme.Coefficients(2, 'Estimate').Estimate;
    lme_means = [lme_means; coef];
    lme_sems = [lme_sems; (lme.Coefficients(2, 'Upper').Upper - lme.Coefficients(2, 'Lower').Lower) / 2];
    lme_ps = [lme_ps; p];
    
    % t-test on fisher z-transformed correlation coefficients
    %
    [h, p, ci, stats] = ttest(fisher_rs);
    ttest_ps = [ttest_ps; p];
    ttest_means = [ttest_means; mean(fisher_rs)];
    ttest_sems = [ttest_sems; (ci(2) - ci(1)) / 2];
    all_fisher_rs{roi} = fisher_rs;
end

%
% LME plots
%
%{
figure;

% plot correlation coefficients for LME
%
subplot(2, 1, 1);

h = bar(lme_means, 'FaceColor', [0.5 0.5 0.5], 'EdgeColor', [0.5 0.5 0.5]);
xs = h(1).XData;
hold on;
errorbar(xs, lme_means, lme_sems, '.', 'MarkerSize', 1, 'MarkerFaceColor', [0 0 0], 'LineWidth', 1, 'Color', [0 0 0], 'AlignVertexCenters', 'off');
hold off;

set(gca, 'xtick', xs);
ylabel('Fixed effect');
xticklabels([strrep(rois, '_', '\_'), repmat({'random'}, 1, size(rand_voxels, 1))]);
xtickangle(60);
xlabel('voxel');
title([plot_what, ' betas correlated with test log likelihood: LME analysis'], 'Interpreter', 'none');

% plot p-values
%
subplot(2, 1, 2);

h = bar(lme_ps, 'FaceColor', [0.5 0.5 0.5], 'EdgeColor', [0.5 0.5 0.5]);
xs = h(1).XData;
hold on;
plot([0 max(xs) + 1],[0.05 0.05],'k--');
hold off;

set(gca, 'xtick', xs);
ylabel('p-value');
xticklabels([strrep(rois, '_', '\_'), repmat({'random'}, 1, size(rand_voxels, 1))]);
xtickangle(60);
xlabel('voxel');
%}

% plot random effects for first ROI
%
%{
subplot(3, 1, 3);

roi_idx = 1;
lme = lmes{roi_idx};

[randMeans, ~, randStats] = randomEffects(lme);
assert(numel(randMeans) == metadata.N * 2);
randSems = (randStats(:, 'Upper').Upper - randStats(:, 'Lower').Lower) / 2;

h = bar(reshape(randMeans, [2 20])', 'FaceColor', [0.5 0.5 0.5], 'EdgeColor', [0.5 0.5 0.5]);
xs = h(1).XData;
xs = sort([xs - 0.2, xs + 0.2])';
hold on;
errorbar(xs, randMeans, randSems, '.', 'MarkerSize', 1, 'MarkerFaceColor', [0 0 0], 'LineWidth', 1, 'Color', [0 0 0], 'AlignVertexCenters', 'off');
hold off;

set(gca, 'xtick', h(1).XData);
ylabel('Random effect');
xtickangle(60);
xlabel('subject');

[fixedMeans, ~, fixedStats] = fixedEffects(lme);
%}


%
% t-test plots
%

figure;

% plot correlation coefficients for t-tests
%
subplot(2, 1, 1);

h = bar(ttest_means, 'FaceColor', [0.5 0.5 0.5], 'EdgeColor', [0.5 0.5 0.5]);
xs = h(1).XData;
hold on;
errorbar(xs, ttest_means, ttest_sems, '.', 'MarkerSize', 1, 'MarkerFaceColor', [0 0 0], 'LineWidth', 1, 'Color', [0 0 0], 'AlignVertexCenters', 'off');
hold off;

set(gca, 'xtick', xs);
ylabel('Fixed effect');
xticklabels([strrep(rois, '_', '\_'), repmat({'random'}, 1, size(rand_voxels, 1))]);
xtickangle(60);
xlabel('voxel');
title([plot_what, ' betas correlated with test log likelihood: t-test'], 'Interpreter', 'none');

% plot p-values
%
subplot(2, 1, 2);

h = bar(ttest_ps, 'FaceColor', [0.5 0.5 0.5], 'EdgeColor', [0.5 0.5 0.5]);
xs = h(1).XData;
hold on;
plot([0 max(xs) + 1],[0.05 0.05],'k--');
hold off;

set(gca, 'xtick', xs);
ylabel('p-value');
xticklabels([strrep(rois, '_', '\_'), repmat({'random'}, 1, size(rand_voxels, 1))]);
xtickangle(60);
xlabel('voxel');



