% Show the KL beta <-> test choice likelihood correlation,
% both for structures and for weights
%

close all;
clear all;

%% Load behavior
%
[data, metadata] = load_data(fullfile('data', 'fmri.csv'), true, getGoodSubjects());
goodSubjects = getGoodSubjects();
which_rows = data.which_rows;

%% Simulate behavior
%
prior_variance = 0.1249;
inv_softmax_temp = 2.0064;
params = [prior_variance inv_softmax_temp];
which_structures = logical([1 1 1 0]);
simulated = simulate_subjects(data, metadata, params, which_structures, which_rows, false);

%% Some random voxels as controls
%
rand_voxels = gen_rand_voxels(fullfile('masks', 'mask.nii'), 20);

%% The KL_weight betas from GLM 148
%

% The peak voxel from each ROI from the contrast (from the results table) 
%
KL_weights_148_rois = {'Temporal_Inf_L', ...
    'Parietal_Inf_L', ...
	'Temporal_Inf_L', ...
	'Supp_Motor_Area_R', ...
	'Frontal_Sup_Medial_L', ...
	'Supp_Motor_Area_L', ...
	'Location not in atlas', ...
	'Location not in atlas', ...
	'Frontal_Inf_Oper_L', ...
	'Frontal_Mid_2_L', ...
	'Frontal_Inf_Tri_R', ...
	'Frontal_Inf_Tri_R', ...
	'Cerebelum_8_R', ...
	'Frontal_Inf_Orb_2_L', ...
	'Pallidum_L', ...
	'Frontal_Inf_Tri_L'};

KL_weights_peak_148_voxels = [-48    -52    -16; ...
	-32    -56    46; ...
	-42    -34    -28; ...
	10    14    46; ...
	-8    22    42; ...
	-8    10    68; ...
	30    24    0; ...
	16    6    -6; ...
	-42    8    26; ...
	-36    4    58; ...
	36    20    28; ...
	50    34    24; ...
	30    -68    -50; ...
	-46    16    -4; ...
	-20    4    -4; ...
	-44    40    0];

KL_weights_148_betas = load_run_betas(148, 'KL_weights', [KL_weights_peak_148_voxels; rand_voxels]);

%% The KL_structures betas, voxels taken from 'surprise - wrong' contrast from GLM 123
%
KL_structures_error_123_rois = {
    'Angular_R', ...
    'Parietal_Inf_R', ...
    'Frontal_Mid_2_L', ...
    'Location not in atlas', ...
    'Frontal_Mid_2_R', ...
    'OFCmed_R', ...
    'Frontal_Mid_2_R'};

KL_structures_error_123_peak_voxels = [34  -68 52; ...
    40  -46 38; ...
    -42 54  2; ...
    -30 62  22; ...
    36  54  0; ...
    18  42  -16; ...
    52  32  32];

KL_structures_error_123_betas = load_run_betas(123, 'surprise', [KL_structures_error_123_peak_voxels; rand_voxels]);

%% KL_structures betas for 'surprise' contrast only from GLM 123
%
KL_structures_123_rois = { ...
    'Parietal_Sup_R', ...
    'Parietal_Inf_R', ...
    'Location', ...
    'Frontal_Inf_Oper_R', ...
    'Frontal_Mid_2_R', ...
    'Frontal_Mid_2_L', ...
    'Frontal_Sup_2_L', ...
    'Frontal_Inf_Orb_2_L', ...
    'Frontal_Mid_2_R', ...
    'OFCant_R', ...
    'Parietal_Inf_L', ...
    'Parietal_Inf_L', ...
    'Cerebelum_Crus2_L', ...
    'Frontal_Inf_Tri_L', ...
    'Precentral_L', ...
    'Frontal_Mid_2_L', ...
    'Cerebelum_8_L', ...
    'Cerebelum_Crus1_L'};

KL_structures_123_peak_voxels = [ ...
    32    -66    50; ...
    42    -46    40; ...
    32    22    0; ...
    48    22    32; ...
    34    12    52; ...
    -40    56    4; ...
    -24    58    -10; ...
    -46    34    -10; ...
    36    54    0; ...
    20    48    -16; ...
    -30    -62    40; ...
    -46    -38    44; ...
    -6    -78    -30; ...
    -38    16    26; ...
    -38    0    40; ...
    -50    34    28; ...
    -32    -68    -54; ...
    -30    -62    -32];

KL_structures_123_betas = load_run_betas(123, 'surprise', [KL_structures_123_peak_voxels; rand_voxels]);


% The KL_structures from the 'KL_structure' contrast from GLM 151 with the KL_weights
% note that this overwrites the previous one
%

KL_structures_151_rois = { ...
    'Insula_R', ...
    'Angular_R', ...
    'Parietal_Inf_R', ...
    'Occipital_Mid_R', ...
    'Parietal_Inf_L', ...
    'Parietal_Inf_L', ...
    'Frontal_Inf_Oper_R', ...
    'Frontal_Mid_2_R', ...
    'Frontal_Mid_2_L', ...
    'Frontal_Sup_2_L', ...
    'Temporal_Pole_Sup_L', ...
    'Precentral_L', ...
    'Frontal_Inf_Tri_L', ...
    'Frontal_Mid_2_L', ...
    'OFCant_R', ...
    'Frontal_Mid_2_R', ...
    'Supp_Motor_Area_L', ...
    'Frontal_Sup_Medial_L', ...
    'Cerebelum_6_R', ...
    'Fusiform_R', ...
    'Temporal_Inf_R', ...
    'Fusiform_L', ...
    'Cerebelum_Crus2_L', ...
    'Cerebelum_8_L', ...
    'Insula_L', ...
    'Temporal_Inf_R', ...
    'Temporal_Inf_R', ...
    'Lingual_R', ...
    'Cuneus_R', ...
    'Temporal_Mid_L', ...
    'Occipital_Inf_L'};

KL_structures_151_peak_voxels = [...
    32    22    0; ...
    34    -64    48; ...
    44    -46    42; ...
    32    -66    26; ...
    -30    -62    40; ...
    -46    -38    42; ...
    48    20    32; ...
    32    12    50; ...
    -40    56    6; ...
    -24    58    -10; ...
    -46    22    -16; ...
    -42    2    32; ...
    -48    20    20; ...
    -38    12    58; ...
    20    48    -16; ...
    36    54    0; ...
    -6    8    52; ...
    -6    34    38; ...
    18    -70    -24; ...
    34    -42    -20; ...
    46    -58    -24; ...
    -32    -54    -18; ...
    -6    -78    -30; ...
    -32    -68    -54; ...
    -28    24    -2; ...
    62    -24    -22; ...
    58    -60    -20; ...
    12    -96    -8; ...
    12    -98    12; ...
    -58    -36    -4; ...
    -20    -92    -6];

KL_structures_151_betas = load_run_betas(151, 'KL_structures', [KL_structures_151_peak_voxels; rand_voxels]);

% The KL_weights from the 'KL_weights' contrast from GLM 151 with the KL_structures
% note that this overwrites the previous one
%

KL_weights_151_rois = { ...
    'Temporal_Inf_L', ...
    'Parietal_Inf_L', ...
    'Fusiform_L', ...
    'Frontal_Inf_Tri_R', ...
    'Frontal_Inf_Oper_L', ...
    'Frontal_Inf_Tri_L', ...
    'Frontal_Mid_2_L', ...
    'Supp_Motor_Area_L', ...
    'Location not in atlas', ...
    'Thalamus_R', ...
    'Putamen_R', ...
    'Temporal_Mid_L', ...
    'Frontal_Inf_Orb_2_L', ...
    'Putamen_L'};

KL_weights_peak_151_voxels = [ ...
    -50    -52    -16; ...
    -26    -68    44; ...
    -28    -72    -18; ...
    36    20    26; ...
    -42    8    26; ...
    -56    22    20; ...
    -38    4    60; ...
    -8    10    50; ...
    30    26    0; ...
    12    -14    2; ...
    16    8    -6; ...
    -54    -38    -4; ...
    -40    20    -4; ...
    -20    16    -6];

KL_weights_151_betas = load_run_betas(151, 'KL_weights', [KL_weights_peak_151_voxels; rand_voxels]);

%% Get the behavioral correlates
%
[test_liks, test_RTs] = get_test_behavior();

save('results/kl_stuff_151.mat');

%% within-subject analysis using a linear mixed effects model and/or t-tests
%

load('results/kl_stuff_151.mat');

correlate_neural_and_behavior(KL_weights_148_betas, [KL_weights_148_rois, repmat({'random'}, 1, size(rand_voxels, 1))], test_liks, 'KL_weight betas (GLM 148) correlated with test log likelihood: t-test');
correlate_neural_and_behavior(KL_structures_123_betas, [KL_structures_123_rois, repmat({'random'}, 1, size(rand_voxels, 1))], test_liks, 'KL_structure betas (GLM 123) correlated with test log likelihood: t-test');

correlate_neural_and_behavior(KL_weights_151_betas, [KL_weights_151_rois, repmat({'random'}, 1, size(rand_voxels, 1))], test_liks, 'KL_weight betas (GLM 151) correlated with test log likelihood: t-test');
correlate_neural_and_behavior(KL_structures_151_betas, [KL_structures_151_rois, repmat({'random'}, 1, size(rand_voxels, 1))], test_liks, 'KL_structure betas (GLM 151) correlated with test log likelihood: t-test');
